version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies for example...
      - cd ./example
      - npm install
      - echo Installing source NPM dependencies...
      - cd ..
      - npm install
      - cd ./example
  build:
    commands:
      - echo Build started on `date`
      - npm run build

artifacts:
  base-directory: ./example/build
  files:
    - "**/*"
