version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source YARN dependencies...
      - cd ./docs
      - pwd
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn build

artifacts:
  base-directory: ./docs/build
  files:
    - "**/*"
